Update IMM for JP-TVbox.yml

diff --git a/.github/workflows/IMM for JP-TVbox.yml b/.github/workflows/IMM for JP-TVbox.yml
--- a/.github/workflows/IMM for JP-TVbox.yml
+++ b/.github/workflows/IMM for JP-TVbox.yml
@@ -35,7 +35,7 @@ jobs:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo -E apt-get -qq update -y
-        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/nantayo/My-Pkg/master/2305)
+        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/jumbotsang/My-Pkg/refs/heads/main/2411)
         sudo -E apt-get -qq autoremove --purge
         sudo -E apt-get -qq clean
         sudo timedatectl set-timezone "$TZ"
@@ -62,6 +62,10 @@ jobs:
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_SH
 
+    - name: SSH connect to Actions
+      uses: P3TERX/ssh2actions@main
+      if: (github.event.inputs.ssh == 'true') || contains(github.event.action, 'ssh')
+
     - name: Download package
       working-directory: ./openwrt
       run: |
@@ -82,7 +86,13 @@ jobs:
       if: ${{ env.compile_status }} == 'success' && !cancelled()
       uses: unifreq/openwrt_packit@master
       env:
-        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
+        OPENWRT_ARMVIRT:  |
+          if ls openwrt/bin/targets/*/*/*.tar.gz 1> /dev/null 2>&1; then
+            echo "$(ls openwrt/bin/targets/*/*/*.tar.gz)"
+          else
+            echo "[ERROR] No .tar.gz file found in the expected directory."
+            exit 1
+          fi
         KERNEL_VERSION_NAME: 6.6.60
         KERNEL_AUTO_LATEST: ture
         PACKAGE_SOC: diy
